services:
  db:
    image: postgres
    container_name: postgres_microservice
    restart: unless-stopped
    environment:
      POSTGRES_DB: springBoot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: myUniquePassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - springBootNetwork

  db_adminer:
    image: adminer
    container_name: adminer_microservice
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - springBootNetwork

networks:
  springBootNetwork:
    name: springBootNetwork


volumes:
  pgdata:
    name: postgress_data
