spring:
  application:
    name: restfulAPIs

  datasource:
    url: jdbc:postgresql://localhost:5432/springBoot
    username: admin
    password: myUniquePassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop' # Options: none, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # database-platform: org.hibernate.dialect.PostgreSQLDialect # REMOVED THIS LINE
    open-in-view: false # Added to disable the default open-in-view behavior and suppress warning

server:
  port: 8081
